"""Scaffold-templates voor een nieuwe Docusaurus-site in het docs-monorepo.

Levert de minimale, bouwbare bestandenset (gemodelleerd naar
sites/informatica/web, dat ook zonder babel.config.js of eigen custom.css bouwt;
@coderius/shared/config verzorgt brand-CSS en -assets). Plus pure tekstmutaties
voor de registers die een nieuwe site (en eventueel een nieuw vak) bekendmaken:
packages/shared/sites.js in het docs-repo en sites.json in het beheer-repo.

Geen CI-matrix en geen Traefik-router meer: de CI-matrix wordt gegenereerd uit
de gewijzigde packages, en één wildcard-router dekt elk vak-domein.
"""

import json
import re

from app.config import site_dir_for

# --- nieuwe site-bestanden -------------------------------------------------


def _package_json(slug: str) -> str:
    data = {
        "name": f"@coderius/{slug}-docs",
        "version": "0.0.0",
        "private": True,
        "scripts": {
            "docusaurus": "docusaurus",
            "start": "docusaurus start",
            "build": "docusaurus build",
            "swizzle": "docusaurus swizzle",
            "serve": "docusaurus serve",
            "clear": "docusaurus clear",
            "write-translations": "docusaurus write-translations",
            "write-heading-ids": "docusaurus write-heading-ids",
            "typecheck": "tsc",
        },
        "dependencies": {
            "@coderius/shared": "workspace:*",
            "@docusaurus/core": "catalog:",
            "@docusaurus/preset-classic": "catalog:",
            "@mdx-js/react": "catalog:",
            "clsx": "catalog:",
            "prism-react-renderer": "catalog:",
            "react": "catalog:",
            "react-dom": "catalog:",
        },
        "devDependencies": {
            "@docusaurus/module-type-aliases": "catalog:",
            "@docusaurus/tsconfig": "catalog:",
            "@docusaurus/types": "catalog:",
            "typescript": "catalog:",
        },
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def _docusaurus_config(
    slug: str, subject: str, path: str, title: str, tagline: str, origin: str, description: str
) -> str:
    # JSON-dump losse strings zodat aanhalingstekens/quotes veilig ontsnapt zijn.
    # url/baseUrl staan er expliciet: de site woont op <vak-domein>/<path>/.
    return f"""import {{createConfig}} from '@coderius/shared/config';

export default createConfig({{
  title: {json.dumps(title)},
  tagline: {json.dumps(tagline)},
  url: {json.dumps(origin)},
  baseUrl: {json.dumps(f"/{path}/")},
  projectName: {json.dumps(f"{slug}-docs")},

  description: {json.dumps(description)},

  presets: [
    [
      'classic',
      {{
        docs: {{
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/Coderius-Education/docs/tree/main/sites/{subject}/{slug}/',
        }},
        blog: false,
      }},
    ],
  ],

  themeConfig: {{
    navbar: {{
      title: {json.dumps(title)},
      logo: {{alt: 'Coderius', src: 'img/logo.svg'}},
      items: [
        {{
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          label: 'Docs',
          position: 'left',
        }},
      ],
    }},
    footer: {{
      style: 'dark',
      links: [
        {{
          title: 'Meer van Coderius',
          items: [
            {{label: 'Alle vakken', href: 'https://coderius.nl'}},
            {{label: 'Dit vak', href: {json.dumps(origin)}}},
          ],
        }},
      ],
    }},
  }},
}});
"""


_SIDEBARS_TS = """import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogegenereerde sidebar: volgt de mappenstructuur onder docs/.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
"""

_TSCONFIG_JSON = """{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": ".docusaurus"
  },
  "include": [
    "src",
    "docusaurus.config.ts"
  ]
}
"""

# The shared runtime consumes the imported MDX frontmatter and keeps one route.
_INDEX_TSX = """import ManagedHomepage from '@coderius/shared/components/ManagedHomepage';
import Content, { frontMatter } from '../content/homepage.mdx';

export default function Home() {
  return <ManagedHomepage Content={Content} frontMatter={frontMatter} />;
}
"""

_HOMEPAGE_MDX = """---
---

import {Hero, Buttons, Button} from '@coderius/shared/components/HomepageSections';

<Hero>
  <Buttons>
    <Button href="/docs/intro">Begin de cursus</Button>
  </Buttons>
</Hero>
"""

_MANAGED_SETTINGS = {"version": 1, "site": {}, "themeConfig": {}, "tokens": {}, "docs": {}}
_CAPABILITIES = {
    "version": 1,
    "framework": "docusaurus",
    "framework_version": "3.10.1",
    "managed_homepage": True,
    "settings_runtime": True,
    "mermaid": False,
    "math": False,
    "homepage_fields": [
        "title",
        "description",
        "keywords",
        "image",
        "slug",
        "wrapperClassName",
        "noFooter",
        "fullscreen",
    ],
}


def _intro_md(title: str) -> str:
    return f"""---
sidebar_position: 1
---

# Welkom bij {title}

Dit is de startpagina van deze nieuwe site. Voeg hier je eerste les toe.
"""


def scaffold_files(
    slug: str,
    title: str,
    tagline: str,
    origin: str,
    description: str,
    *,
    subject: str = "informatica",
    path: str | None = None,
) -> dict[str, bytes]:
    """Pad (in het docs-repo) -> inhoud (bytes) voor een minimale nieuwe site.

    `origin` is het vak-domein met schema (https://informatica.coderius.nl); de
    site woont op `<origin>/<path>/`.
    """
    path = path or slug
    base = site_dir_for(subject, slug)
    files = {
        f"{base}/package.json": _package_json(slug),
        f"{base}/docusaurus.config.ts": _docusaurus_config(
            slug, subject, path, title, tagline, origin, description
        ),
        f"{base}/sidebars.ts": _SIDEBARS_TS,
        f"{base}/tsconfig.json": _TSCONFIG_JSON,
        f"{base}/src/pages/index.tsx": _INDEX_TSX,
        f"{base}/src/content/homepage.mdx": _HOMEPAGE_MDX,
        f"{base}/site-settings.json": json.dumps(_MANAGED_SETTINGS, indent=2) + "\n",
        f"{base}/authoring-capabilities.json": json.dumps(_CAPABILITIES, indent=2) + "\n",
        f"{base}/src/css/managed-theme.css": "/* Generated from site-settings.json. */\n",
        f"{base}/docs/intro.md": _intro_md(title),
    }
    return {p: content.encode("utf-8") for p, content in files.items()}


# --- registers ---------------------------------------------------------------


def _dump_registry(registry: dict) -> str:
    """sites.json in de vaste stijl: één regel per vak en per site (diff-vriendelijk)."""

    def line(item: dict) -> str:
        return json.dumps(item, ensure_ascii=False)

    def block(items: list[dict]) -> str:
        return ",\n".join(f"    {line(item)}" for item in items)

    return (
        "{\n"
        f'  "apex": {json.dumps(registry["apex"])},\n'
        f'  "subjects": [\n{block(registry["subjects"])}\n  ],\n'
        f'  "sites": [\n{block(registry["sites"])}\n  ]\n'
        "}\n"
    )


def add_subject_to_registry(sites_json: str, subject: str, domain: str, display_name: str) -> str:
    registry = json.loads(sites_json)
    if any(s["slug"] == subject for s in registry["subjects"]):
        raise ValueError(f"Vak '{subject}' staat al in sites.json")
    registry["subjects"].append({"slug": subject, "domain": domain, "display_name": display_name})
    return _dump_registry(registry)


def add_site_to_registry(
    sites_json: str, slug: str, subject: str, path: str, display_name: str
) -> str:
    """Voegt een site toe aan sites.json, vóór `home` (die blijft de laatste)."""
    registry = json.loads(sites_json)
    if any(s["slug"] == slug for s in registry["sites"]):
        raise ValueError(f"Site '{slug}' staat al in sites.json")
    if not any(s["slug"] == subject for s in registry["subjects"]):
        raise ValueError(f"Onbekend vak '{subject}' in sites.json")
    if any(s.get("subject") == subject and s.get("path") == path for s in registry["sites"]):
        raise ValueError(f"Pad '/{path}/' is al in gebruik binnen '{subject}'")
    entry = {
        "slug": slug,
        "subject": subject,
        "path": path,
        "display_name": display_name,
        "legacy_domains": [],
    }
    sites = registry["sites"]
    home = next((i for i, s in enumerate(sites) if s["slug"] == "home"), len(sites))
    sites.insert(home, entry)
    return _dump_registry(registry)


def _js_str(value: str) -> str:
    """JS-stringliteral met enkele quotes (huisstijl van sites.js)."""
    escaped = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{escaped}'"


def _append_to_js_array(source: str, name: str, entry: str) -> str:
    """Voegt `entry` toe als laatste element van `const <name> = [ … ];`."""
    match = re.search(rf"const {name} = \[\n", source)
    if match is None:
        raise ValueError(f"Kon `const {name} = [` niet vinden in sites.js")
    end = source.find("\n];", match.end() - 1)
    if end == -1:
        raise ValueError(f"Kon het einde van {name} niet vinden in sites.js")
    return source[:end] + "\n" + entry.rstrip("\n") + source[end:]


def add_subject_to_sites_js(sites_js: str, subject: str, domain: str, display_name: str) -> str:
    if re.search(rf"id: '{re.escape(subject)}'", sites_js):
        raise ValueError(f"Vak '{subject}' staat al in sites.js")
    entry = (
        f"  {{ id: {_js_str(subject)}, label: {_js_str(display_name)}, "
        f"url: {_js_str(f'https://{domain}')} }},"
    )
    return _append_to_js_array(sites_js, "SUBJECTS", entry)


def add_site_to_sites_js(
    sites_js: str, slug: str, subject: str, path: str, label: str, description: str
) -> str:
    """Nieuwe cursus achteraan in SITES (de leerlijn-volgorde zet een docent later goed)."""
    if re.search(rf"id: '{re.escape(slug)}'", sites_js):
        raise ValueError(f"Site '{slug}' staat al in sites.js")
    entry = (
        "  {\n"
        f"    id: {_js_str(slug)},\n"
        f"    subject: {_js_str(subject)},\n"
        f"    path: {_js_str(path)},\n"
        f"    label: {_js_str(label)},\n"
        f"    description: {_js_str(description)},\n"
        "    requires: [],\n"
        "  },"
    )
    return _append_to_js_array(sites_js, "SITES", entry)
