"""Scaffold-templates voor een nieuwe Docusaurus-site in het docs-monorepo.

Levert de minimale, bouwbare bestandenset (gemodelleerd naar sites/web, dat ook
zonder babel.config.js of eigen custom.css bouwt — @coderius/shared/config
verzorgt brand-CSS en -assets). Plus pure tekstmutaties voor de bestaande
bestanden die een nieuwe site registreren: de CI-matrix en de Traefik-routing.
"""

import json
import re

# --- nieuwe site-bestanden -------------------------------------------------


def _package_json(slug: str) -> str:
    data = {
            "name": f"@coderius/{slug}-docs",
            "version": "0.0.0",
            "private": True,
            "scripts": {
                "docusaurus": "docusaurus",
                "start": "docusaurus start",
                "build": "docusaurus build",
                "swizzle": "docusaurus swizzle",
                "serve": "docusaurus serve",
                "clear": "docusaurus clear",
                "write-translations": "docusaurus write-translations",
                "write-heading-ids": "docusaurus write-heading-ids",
                "typecheck": "tsc",
            },
            "dependencies": {
                "@coderius/shared": "workspace:*",
                "@docusaurus/core": "catalog:",
                "@docusaurus/preset-classic": "catalog:",
                "@mdx-js/react": "catalog:",
                "clsx": "catalog:",
                "prism-react-renderer": "catalog:",
                "react": "catalog:",
                "react-dom": "catalog:",
            },
            "devDependencies": {
                "@docusaurus/module-type-aliases": "catalog:",
                "@docusaurus/tsconfig": "catalog:",
                "@docusaurus/types": "catalog:",
                "typescript": "catalog:",
            },
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def _docusaurus_config(slug: str, title: str, tagline: str, domain: str, description: str) -> str:
    # JSON-dump losse strings zodat aanhalingstekens/quotes veilig ontsnapt zijn.
    return f"""import {{createConfig}} from '@coderius/shared/config';

export default createConfig({{
  title: {json.dumps(title)},
  tagline: {json.dumps(tagline)},
  url: {json.dumps(f"https://{domain}")},
  projectName: {json.dumps(f"{slug}-docs")},

  description: {json.dumps(description)},

  presets: [
    [
      'classic',
      {{
        docs: {{
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/Coderius-Education/{slug}-docs/tree/main/',
        }},
        blog: false,
      }},
    ],
  ],

  themeConfig: {{
    navbar: {{
      title: {json.dumps(title)},
      logo: {{alt: 'Coderius', src: 'img/logo.svg'}},
      items: [
        {{
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          label: 'Docs',
          position: 'left',
        }},
        {{
          href: 'https://github.com/Coderius-Education/{slug}',
          label: 'GitHub',
          position: 'right',
        }},
      ],
    }},
    footer: {{
      style: 'dark',
      links: [
        {{
          title: 'Meer van Coderius',
          items: [
            {{label: 'Leer Python', href: 'https://python.coderius.nl'}},
            {{label: 'Webontwikkeling', href: 'https://web.coderius.nl'}},
          ],
        }},
      ],
    }},
  }},
}});
"""


_SIDEBARS_TS = """import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogegenereerde sidebar: volgt de mappenstructuur onder docs/.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
"""

_TSCONFIG_JSON = """{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": ".docusaurus"
  },
  "include": [
    "src",
    "docusaurus.config.ts"
  ]
}
"""

# Zelfstandige homepage zonder lokale component-/CSS-afhankelijkheden, zodat de
# site bouwt met alleen de gescaffolde bestanden.
_INDEX_TSX = """import type {ReactNode} from 'react';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className="hero hero--primary">
      <div className="container">
        <Heading as="h1" className="hero__title">
          {siteConfig.title}
        </Heading>
        <p className="hero__subtitle">{siteConfig.tagline}</p>
        <div>
          <Link className="button button--secondary button--lg" to="/docs/intro">
            Begin de cursus
          </Link>
        </div>
      </div>
    </header>
  );
}

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout title={siteConfig.title} description={siteConfig.tagline}>
      <HomepageHeader />
    </Layout>
  );
}
"""


def _intro_md(title: str) -> str:
    return f"""---
sidebar_position: 1
---

# Welkom bij {title}

Dit is de startpagina van deze nieuwe site. Voeg hier je eerste les toe.
"""


def scaffold_files(
    slug: str, title: str, tagline: str, domain: str, description: str
) -> dict[str, bytes]:
    """Pad (in het docs-repo) -> inhoud (bytes) voor een minimale nieuwe site."""
    base = f"sites/{slug}"
    files = {
        f"{base}/package.json": _package_json(slug),
        f"{base}/docusaurus.config.ts": _docusaurus_config(
            slug, title, tagline, domain, description
        ),
        f"{base}/sidebars.ts": _SIDEBARS_TS,
        f"{base}/tsconfig.json": _TSCONFIG_JSON,
        f"{base}/src/pages/index.tsx": _INDEX_TSX,
        f"{base}/docs/intro.md": _intro_md(title),
    }
    return {path: content.encode("utf-8") for path, content in files.items()}


# --- mutaties op bestaande bestanden ---------------------------------------


def add_site_to_build_matrix(build_yml: str, slug: str) -> str:
    """Voegt de slug toe aan de `site:`-matrix in .github/workflows/build.yml.

    Ingevoegd als eerste matrix-item direct na de `site:`-sleutel; volgorde doet
    er voor de matrix niet toe en dit anker is uniek in het bestand.
    """
    anchor = "        site:\n"
    if anchor not in build_yml:
        raise ValueError("Kon de site-matrix in build.yml niet vinden")
    return build_yml.replace(anchor, f"{anchor}          - {slug}\n", 1)


def add_site_to_registry(sites_json: str, slug: str, domain: str, display_name: str) -> str:
    """Voegt een site toe aan sites.json (behoudt 2-spatie-indent + newline)."""
    registry = json.loads(sites_json)
    if any(s["slug"] == slug for s in registry):
        raise ValueError(f"Site '{slug}' staat al in sites.json")
    registry.append({"slug": slug, "domain": domain, "display_name": display_name})
    return json.dumps(registry, indent=2, ensure_ascii=False) + "\n"


def _router_name(domain: str) -> str:
    """Traefik-routernaam afgeleid van het domein: uniek, alleen [a-z0-9-]."""
    return "docsite-" + re.sub(r"[^a-z0-9]+", "-", domain.lower()).strip("-")


def add_domain_to_traefik(compose_yml: str, domain: str) -> str:
    """Voegt een eigen Traefik-router toe voor `domain`, met een eigen
    certresolver. Elk domein een aparte router betekent ook een aparte
    certificaataanvraag, zodat een mislukt cert voor één domein de andere sites
    niet meesleurt. We ankeren op de (unieke) service-loadbalancer-regel en
    voegen het routerblok daar vlak vóór in."""
    anchor = "      - traefik.http.services.docsdelivery.loadbalancer.server.port=8000"
    if anchor not in compose_yml:
        raise ValueError("Kon de docsdelivery-service-regel in compose.yml niet vinden")
    name = _router_name(domain)
    if f"traefik.http.routers.{name}." in compose_yml:
        raise ValueError(f"Router voor domein '{domain}' staat al in compose.yml")
    block = (
        f"\n"
        f"      - traefik.http.routers.{name}.rule=Host(`{domain}`)\n"
        f"      - traefik.http.routers.{name}.entrypoints=websecure\n"
        f"      - traefik.http.routers.{name}.tls.certresolver=leresolver\n"
        f"      - traefik.http.routers.{name}.service=docsdelivery\n"
    )
    return compose_yml.replace(anchor, block + anchor, 1)
